version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: writebeyonddb
    ports:
      - "5432:5432"
    networks:
      - write-beyond
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend/write-beyond
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/writebeyonddb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - write-beyond
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: react-frontend
    stdin_open: true
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://backend:8080
    networks:
      - write-beyond
    depends_on:
      - backend
    restart: unless-stopped
networks:
  write-beyond:
    driver: bridge
volumes:
  postgres-data:
